"""Differentially validate project qualification on trusted constructed controls.

The target snippets are generated by ``make_controls.py`` and are safe to
execute locally.  This script compares the non-executing project analyzer with
CPython/Babel runtime outcomes over every count in 0..200.  It validates the
flow/type analysis; it is not field-defect evidence.
"""
from __future__ import annotations

from pathlib import Path
import json

if __package__:
    from . import _repo_bootstrap  # noqa: F401
else:
    import _repo_bootstrap  # noqa: F401

from msgbranch.project import audit_project
from msgbranch.runtime import CatalogRuntime

ROOT = Path(__file__).resolve().parents[1]

def reference(source: str, runtime: CatalogRuntime, n: int) -> dict:
    env = {
        "gettext": runtime.gettext,
        "_": runtime.gettext,
        "ngettext": runtime.ngettext,
        "pgettext": runtime.pgettext,
        "npgettext": runtime.npgettext,
    }
    exec(compile(source, "<trusted-control>", "exec"), env)
    runtime.reset()
    try:
        output = env["message"](n)
        return {"status": "ok", "output": output, "error_type": None}
    except (KeyError, TypeError, ValueError, IndexError, OverflowError) as exc:
        return {"status": "error", "output": None, "error_type": type(exc).__name__}


def has_failure(result: dict, spec: dict) -> bool:
    if result["status"] == "error":
        return True
    if spec.get("contains") == "count" and result["status"] == "ok":
        return result["output"] != f"{result['n']} {'item' if result['n'] == 1 else 'items'}"
    return False


DOMAIN = list(range(201))


def expand_ranges(ranges: list[list[int | None]]) -> set[int]:
    counts: set[int] = set()
    for start, end in ranges:
        if start is None or end is None:
            continue
        counts.update(range(int(start), int(end) + 1))
    return counts


def classified_counts(report: dict, status: str) -> set[int]:
    result: set[int] = set()
    for finding in report["findings"]:
        for witness in finding.get("witnesses", []):
            if witness["qualification"]["status"] == status:
                ranges = witness.get("covered_count_ranges", [])
                if ranges == [[None, None]]:
                    result.update(DOMAIN)
                else:
                    result.update(expand_ranges(ranges))
    return result


def evaluate() -> dict:
    manifest = json.loads((ROOT / "data/control-manifest.json").read_text(encoding="utf-8"))
    rows = []
    for spec in manifest:
        source_path = ROOT / spec["source"]
        catalog_path = ROOT / spec["catalog"]
        source = source_path.read_text(encoding="utf-8")
        runtime = CatalogRuntime(catalog_path)
        actual_failures = {
            n
            for n in DOMAIN
            if has_failure({"n": n, **reference(source, runtime, n)}, spec)
        } if not spec.get("expected_project_unknown", spec["expected_unknown"]) else set()
        flow = audit_project(source_path, [catalog_path], max_count=200, analysis_mode="flow")
        direct = audit_project(source_path, [catalog_path], max_count=200, analysis_mode="direct")
        flow_errors = classified_counts(flow, "error")
        direct_errors = classified_counts(direct, "error")
        flow_unknown = flow["summary"]["unknown"] > 0
        direct_unknown = direct["summary"]["unknown"] > 0
        expected_unknown = bool(spec.get("expected_project_unknown", spec["expected_unknown"]))
        flow_exact = flow_unknown == expected_unknown and (expected_unknown or flow_errors == actual_failures)
        direct_exact = direct_unknown == expected_unknown and (expected_unknown or direct_errors == actual_failures)
        rows.append(
            {
                "case": spec["id"],
                "category": spec["category"],
                "expected_unknown": expected_unknown,
                "actual_failure_counts": sorted(actual_failures),
                "flow_error_counts": sorted(flow_errors),
                "direct_error_counts": sorted(direct_errors),
                "flow_unknown": flow_unknown,
                "direct_unknown": direct_unknown,
                "flow_exact": flow_exact,
                "direct_exact": direct_exact,
                "flow_selected_products": flow["summary"]["selected_patterns"],
                "flow_recovered_calls": flow["summary"]["flow_recovered_calls"],
            }
        )
    known = [row for row in rows if not row["expected_unknown"]]
    result = {
        "summary": {
            "controls": len(rows),
            "known_controls": len(known),
            "unknown_controls": len(rows) - len(known),
            "runtime_executions": len(known) * len(DOMAIN),
            "flow_exact": sum(row["flow_exact"] for row in rows),
            "direct_exact": sum(row["direct_exact"] for row in rows),
            "flow_known_exact": sum(row["flow_exact"] for row in known),
            "direct_known_exact": sum(row["direct_exact"] for row in known),
            "flow_false_positive_controls": sum(
                bool(row["flow_error_counts"]) and not row["actual_failure_counts"] for row in known
            ),
            "flow_false_negative_controls": sum(
                row["flow_error_counts"] != row["actual_failure_counts"]
                and bool(set(row["actual_failure_counts"]) - set(row["flow_error_counts"]))
                for row in known
            ),
            "status": "pass" if all(row["flow_exact"] for row in rows) else "fail",
            "scope": "Trusted constructed controls only; validates static qualification against direct runtime, not field recall.",
        },
        "records": rows,
    }
    return result


def main() -> None:
    result = evaluate()
    (ROOT / "results/flow-validation.json").write_text(
        json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps(result["summary"], ensure_ascii=False, indent=2))
    if result["summary"]["status"] != "pass":
        raise SystemExit(1)


if __name__ == "__main__":
    main()
