"""A disclosed generated validation study, not held-out field defects.

Freeze a hash of the planner before generating cases. Retain all generated pairs,
including undetectable/inactive faults if any. Oracles come from actual direct
Python/native-gettext execution, not expected mutant positions. Only generated
local code is executed. No application service, network or model call is made.
"""
from pathlib import Path
from io import BytesIO
from hashlib import sha256
from babel.messages.catalog import Catalog
from babel.messages.pofile import write_po
import json, gzip, random, time, statistics, math, sys, gettext
from datetime import datetime, timezone
import babel, platform
if __package__:
    from . import _repo_bootstrap  # noqa: F401
else:
    import _repo_bootstrap  # noqa: F401

from msgbranch.partition import GuardPartition, plan_partition
from msgbranch.program import Program, representatives, signature, Unsupported
from msgbranch.runtime import CatalogRuntime
from evaluate import reference
ROOT=Path(__file__).resolve().parents[1]
SEED=260930
LOCALES=['en','fr','ja','ru','ar','pl','cs','sl','lt','lv','ro','ga']
HIGH=1000

def generate():
    root=ROOT/'data/validation';root.mkdir(exist_ok=True)
    freeze={'seed':SEED,'domain':[0,HIGH], 'locales':LOCALES,
            'planner_sha256':sha256((ROOT/'src/msgbranch/partition.py').read_bytes()).hexdigest(),
            'implementation_sha256':{f:sha256((ROOT/'src/msgbranch'/f).read_bytes()).hexdigest() for f in ['partition.py','program.py','runtime.py']},
            'generator_sha256':sha256(Path(__file__).read_bytes()).hexdigest(),
            'environment':{'python':platform.python_version(),'babel':babel.__version__},
            'status':'generated validation, not independent field holdout; operator families known',
            'protocol':'8 guard families x 12 locales x paired clean/mutant; every generated pair retained; 100 uniform-random seeds per equal final execution budget'}
    (root/'protocol.json').write_text(json.dumps(freeze,indent=2)+'\n', encoding='utf-8', newline='\n')
    rng=random.Random(SEED); manifest=[]
    for locale in LOCALES:
        for op in range(8):
            t=rng.randint(37,743); u=rng.randint(t+8,min(973,t+133)); r=rng.randrange(7)
            guard=[f'n == {t}',f'n >= {t} and n < {t+7}',f'n % 7 == {r}',
                   f'n > {t} and n % 7 == {r}',f'not (n < {t} or n >= {t+3})',
                   f'n == {t} or n == {u}',f'{t} <= n and n <= {u}',f'{t} <= n < {t+2}'][op]
            catalog=Catalog(locale=locale,creation_date=datetime(2026,9,30,tzinfo=timezone.utc))
            need=rng.randrange(catalog.num_plurals)
            singular='%(n)d %(owner)s item'; plural='%(n)d %(owner)s items'
            strings=tuple(f'P{i}: %(n)d'+(' / %(owner)s' if i==need else '') for i in range(catalog.num_plurals))
            catalog.add((singular,plural),strings,flags={'python-format'})
            fp=BytesIO();write_po(fp,catalog,omit_header=False)
            # Fixed timestamps in fixture header keep generated bytes deterministic.
            po=fp.getvalue().decode().splitlines()
            po=[line for line in po if not line.startswith(('"POT-Creation-Date:','"PO-Revision-Date:'))]
            base=f'{locale}-{op}'
            folder=root/base;folder.mkdir(exist_ok=True)
            (folder/'messages.po').write_text('\n'.join(po)+'\n', encoding='utf-8', newline='\n')
            for mutant in (False,True):
                name=base+('-mutant' if mutant else '-clean')
                yes='{"n": n}' if mutant else '{"n": n, "owner": "Ada", "unused": "x"}'
                src=f'def message(n):\n    msg = ngettext({singular!r}, {plural!r}, n)\n    args = {yes} if {guard} else {{"n": n, "owner": "Ada"}}\n    return msg % args\n'
                path=folder/('mutant.py' if mutant else 'clean.py');path.write_text(src, encoding='utf-8', newline='\n')
                manifest.append({'id':name,'pair':base,'category':'mutation' if mutant else 'legitimate',
                                 'locale':locale,'operator':op,'guard':guard,'demand_index':need,
                                 'source':path.relative_to(ROOT).as_posix(), 'catalog':(folder/'messages.po').relative_to(ROOT).as_posix()})
    (root/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n', encoding='utf-8', newline='\n')
    return manifest

def selection(p,rt,high,source_only=False,branch_only=False):
    if not source_only:return plan_partition(p,rt,high=high,call_aware=not branch_only)
    q=GuardPartition(0,high);q.add_program(p); seen={}
    for c in q.cells():
        out=p.run(rt,c.witness,plan=True)
        key=json.dumps(out.path,sort_keys=True)
        seen.setdefault(key,c.witness)
    return list(seen.values())

def main():
    manifest=generate(); summaries=[]; selections=[]; nref=0; nplan=0; disagreements=[]
    outdir=ROOT/'results';outdir.mkdir(exist_ok=True)
    rawfile=outdir/'validation-runs.jsonl.gz'
    with rawfile.open('wb') as physical, gzip.GzipFile(filename='',mode='wb',fileobj=physical,mtime=0) as raw:
        for ix,c in enumerate(manifest):
            src=(ROOT/c['source']).read_text();p=Program(src);rt=CatalogRuntime(ROOT/c['catalog'])
            start=time.perf_counter_ns();plan=selection(p,rt,HIGH);plan_ms=(time.perf_counter_ns()-start)/1e6
            branch=selection(p,rt,HIGH,branch_only=True).representatives
            source=selection(p,rt,HIGH,source_only=True)
            proposed=set(plan.representatives); budget=len(proposed)
            selected_rows=[p.run(rt,n).to_dict() for n in sorted(proposed)]
            selections.append({'case':c['id'],'plan':plan.to_dict(),'selected':selected_rows})
            direct=gettext.GNUTranslations(BytesIO(rt.mo))
            env={'gettext':direct.gettext, '_':direct.gettext, 'ngettext':direct.ngettext}
            exec(compile(src,'<trusted-generated-validation>', 'exec'),env)
            ref_fn=env['message']
            outcomes={}; seen_plans={}; signature_ids={}; missed=[]
            for n in range(HIGH+1):
                result=p.run(rt,n).to_dict()
                try:
                    ref={'status':'ok','output':ref_fn(n),'error_type':None}
                except (KeyError,TypeError,ValueError,IndexError,OverflowError) as exc:
                    ref={'status':'error','output':None,'error_type':type(exc).__name__}
                nref+=1
                if result['status']!=ref['status'] or result['output']!=ref['output'] or (result['status']=='error' and not result['error'].startswith(ref['error_type']+':')):
                    disagreements.append([c['id'],n])
                observed=p.run(rt,n,plan=True); nplan+=1
                sig=signature(observed); seen_plans.setdefault(sig,n)
                signature_ids.setdefault(sig,len(signature_ids))
                row={'case':c['id'],'n':n,'status':result['status'],'output':result['output'],'error':result['error'],'signature':signature_ids[sig]}
                raw.write((json.dumps(row,ensure_ascii=False)+'\n').encode())
                outcomes[n]=result['status']=='error'
            observed_sigs={signature(p.run(rt,n,plan=True)) for n in proposed}
            missed=[x for s,x in seen_plans.items() if s not in observed_sigs]
            assert not missed,(c['id'],missed[:10])
            fails={n for n,b in outcomes.items() if b}
            assert c['category']!='legitimate' or not fails,c['id']
            evenly=sorted({round(i*HIGH/(budget-1)) for i in range(budget)}) if budget>1 else [HIGH//2]
            random_results=[]
            for seed in range(100):
                vals=random.Random(f'{SEED}:{c["id"]}:{seed}').sample(range(HIGH+1),budget)
                random_results.append({'seed':seed,'values':vals,'detects':bool(fails.intersection(vals))})
            exact=1-math.prod((HIGH+1-len(fails)-i)/(HIGH+1-i) for i in range(budget)) if budget<=HIGH+1-len(fails) else 1.0
            summaries.append({**c,'domain_size':HIGH+1,'failures':len(fails),'active_mutation':c['category']=='mutation' and bool(fails),
                'representatives':sorted(proposed),'budget':budget,'planning_calls':plan.planning_calls,'cell_evaluations':plan.cell_evaluations,'period':plan.period,
                'predicate_signature_count':len(seen_plans),'missing_signatures':missed,
                'ordinary2_detects':bool(fails.intersection([1,2])),
                'ordinary7_detects':bool(fails.intersection([0,1,2,5,11,21,100])),
                'branch_only_detects':bool(fails.intersection(branch)), 'branch_only_values':branch,
                'source_only_detects':bool(fails.intersection(source)), 'source_only_values':source,
                'product_detects':bool(fails.intersection(proposed)),
                'equal_budget_even_detects':bool(fails.intersection(evenly)),'even_values':evenly,
                'random_detection_probability_exact':exact,'random_trials':random_results,
                'babel_alarm':bool(rt.checks),'babel_checks':rt.checks,'planning_ms':plan_ms})
            if ix%24==0:print('validation',ix,len(manifest),file=sys.stderr)
    assert not disagreements,disagreements[:10]
    # Keep exact inactive cases, rather than discard them to inflate mutation recall.
    active=[r for r in summaries if r['active_mutation']]; legit=[r for r in summaries if r['category']=='legitimate']
    total={'families':len(summaries),'paired_designs':len(manifest)//2,'legitimate':len(legit),
      'mutations':len(manifest)//2,'active_mutations':len(active),'inactive_mutations':len(manifest)//2-len(active),
      'domain_size':HIGH+1,'native_reference_comparisons':nref,'exhaustive_signature_checks':nplan,
      'reference_disagreements':len(disagreements),'signature_disagreements':sum(len(r['missing_signatures']) for r in summaries),
      'active_mutation_detection':{k:sum(r[k] for r in active) for k in ['ordinary2_detects','ordinary7_detects','branch_only_detects','source_only_detects','product_detects','equal_budget_even_detects','babel_alarm']},
      'random_expected_detections':sum(r['random_detection_probability_exact'] for r in active),
      'random_total_hits':sum(q['detects'] for r in active for q in r['random_trials']), 'random_trials_per_family':100,
      'legitimate_runtime_alarms':sum(r['failures']>0 for r in legit),
      'legitimate_babel_alarms':sum(r['babel_alarm'] for r in legit),
      'planning_calls':sum(r['planning_calls'] for r in summaries),
      'cell_evaluations':sum(r['cell_evaluations'] for r in summaries),
      'selected_executions':sum(r['budget'] for r in summaries),
      'median_planning_calls':statistics.median(r['planning_calls'] for r in summaries),
      'max_planning_calls':max(r['planning_calls'] for r in summaries)}
    (outdir/'validation.json').write_text(json.dumps(summaries,indent=2)+'\n', encoding='utf-8', newline='\n')
    (outdir/'validation-selected.json').write_text(json.dumps(selections,indent=2)+'\n', encoding='utf-8', newline='\n')
    (outdir/'validation-summary.json').write_text(json.dumps(total,indent=2)+'\n', encoding='utf-8', newline='\n')
    print(json.dumps(total,indent=2))
if __name__=='__main__':main()
